### ISSUE TITLE
Error in running gan_language.py

### ISSUE THREAD

**Issue by younglululu** [igul222/improved_wgan_training#14]
Hi, I have the following error in running gan_language.py. Any solution to this? I am using tensorflow v0.9

loaded 10000000 lines in dataset
Traceback (most recent call last):
  File "gan_language.py", line 89, in <module>
    fake_inputs = Generator(BATCH_SIZE)
  File "gan_language.py", line 65, in Generator
    output = ResBlock('Generator.1', output)
  File "gan_language.py", line 56, in ResBlock
    output = lib.ops.conv1d.Conv1D(name+'.1', DIM, DIM, 5, output)
  File "/auto/cmb-panasas2/ylu465/program/deeplearning/improved_wgan_training-master/tflib/ops/conv1d.py", line 93, in Conv1D
    data_format='NCHW'
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1204, in conv1d
    data_format=data_format)
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 230, in conv2d_shape
    input_shape[3].assert_is_compatible_with(filter_shape[2])
  File "/auto/cmb-panasas2/ylu465/anaconda/envs/dl_env/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 108, in assert_is_compatible_with
    % (self, other))
ValueError: Dimensions 1 and 512 are not compatible

**Comment by younglululu** [comment]
solved by upgrade tensorflow from 0.9.0 to 1.0.1
