### ISSUE TITLE
cifar10 IOError: [Errno 2] No that directory: 'cifar10/data_batch_1

### ISSUE THREAD

**Issue by Designbook1** [igul222/improved_wgan_training#15]
when run: python gan_cifar10 get that error.
My cifar:
batches.meta.txt  data_batch_2.bin  data_batch_4.bin  readme.html
data_batch_1.bin  data_batch_3.bin  data_batch_5.bin  test_batch.bin

when change cifar10.py : cifar_generator(['data_batch_1','data_batch_2','data_batch_3','data_batch_4','data_batch_5'], batch_size, data_dir), cifar_generator(['test_batch'], batch_size, data_dir)
to
 cifar_generator(['data_batch_1.bin','data_batch_2.bin','data_batch_3.bin','data_batch_4.bin','data_batch_5'], batch_size, data_dir), cifar_generator(['test_batch.bin'], batch_size, data_dir)

I get another error:
Traceback (most recent call last):
  File "gan_cifar.py", line 171, in <module>
    train_gen, dev_gen = lib.cifar10.load(BATCH_SIZE, data_dir=DATA_DIR)
  File "/mnt/data1/daniel/codes/GAN/improved_wgan_training/tflib/cifar10.py", line 32, in load
    cifar_generator(['data_batch_1.bin','data_batch_2.bin','data_batch_3.bin','data_batch_4.bin','data_batch_5.bin'], batch_size, data_dir), 
  File "/mnt/data1/daniel/codes/GAN/improved_wgan_training/tflib/cifar10.py", line 17, in cifar_generator
    all_data.append(unpickle(data_dir + '/' + filename))
  File "/mnt/data1/daniel/codes/GAN/improved_wgan_training/tflib/cifar10.py", line 10, in unpickle
    dict = pickle.load(fo)
cPickle.UnpicklingError: invalid load key, ''.

Waiting your reply, thanks a lot.

**Comment by jaycode** [comment]
I got the same error when mistakenly downloaded cifar100 dataset. Make sure the files are correct.
