### ISSUE TITLE
gan_mnist.py's ERROR

### ISSUE THREAD

**Issue by yihangzhao** [igul222/improved_wgan_training#94]
when i **python gan_mnist.py** show some errors,can anyone solve the problem？Thank you very much.
`Traceback (most recent call last):
  File "gan_mnist.py", line 107, in <module>
    fake_data = Generator(BATCH_SIZE)
  File "gan_mnist.py", line 68, in Generator
    output = lib.ops.deconv2d.Deconv2D('Generator.2', 4*DIM, 2*DIM, 5, output)
  File "C:\Users\Tony\Downloads\improved_wgan_training\tflib\ops\deconv2d.py", line 102, in Deconv2D
    padding='SAME'
  File "D:\Anaconda3\envs\mytf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Anaconda3\envs\mytf\lib\site-packages\tensorflow\python\util\dispatch.py", line 1170, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Got an unexpected keyword argument 'value'`

**Comment by yihangzhao** [comment]
My environment  as follows:

`tensorflow version:'2.10.0'
CUDA Version: 11.3
OS:windows10`
